### ISSUE TITLE
Please try again or make sure your Internet connection is on.

### ISSUE THREAD

**Issue by yinjiahuidada** [xinyu1205/Recognize_Anything-Tag2Text#18]
When I use the RAM Inference demo. Something wrong. How can I fix this error.

Traceback (most recent call last):
  File "inference_ram.py", line 52, in <module>
    model = ram(pretrained=args.pretrained,
  File "/home/developments/Recognize_Anything-Tag2Text/models/tag2text.py", line 476, in ram
    model = RAM(**kwargs)
  File "/home/developments/Recognize_Anything-Tag2Text/models/tag2text.py", line 103, in __init__
    self.tokenizer = init_tokenizer()
  File "/home/developments/Recognize_Anything-Tag2Text/models/utils.py", line 131, in init_tokenizer
    tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')
  File "/root/anaconda3/envs/image2label/lib/python3.8/site-packages/transformers/tokenization_utils_base.py", line 1695, in from_pretrained
    resolved_vocab_files[file_id] = cached_path(
  File "/root/anaconda3/envs/image2label/lib/python3.8/site-packages/transformers/file_utils.py", line 1776, in cached_path
    output_path = get_from_cache(
  File "/root/anaconda3/envs/image2label/lib/python3.8/site-packages/transformers/file_utils.py", line 2000, in get_from_cache
    raise ValueError(
ValueError: Connection error, and we cannot find the requested files in the cached path. Please try again or make sure your Internet connection is on.

**Comment by lvboodvl** [comment]
@yinjiahuidada hello, I meet the same problem, and switch to transformer offine mode as below:
TRANSFORMERS_OFFLINE=1 python inference_ram.py  --image images/1641173_2291260800.jpg --pretrained pretrained/ram_swin_large_14m.pth

**Comment by lcc815** [comment]
@lvboodvl thanks for your solutions, but i still got the following errors following your way
```
Traceback (most recent call last):
  File "inference_ram.py", line 43, in <module>
    model = ram(pretrained=args.pretrained,
  File "/mnt/csi-data-aly/user/*/recognize-anything/ram/models/ram.py", line 263, in ram
    model = RAM(**kwargs)
  File "/mnt/csi-data-aly/user/*/recognize-anything/ram/models/ram.py", line 103, in __init__
    self.tokenizer = init_tokenizer()
  File "/mnt/csi-data-aly/user/*/recognize-anything/ram/models/utils.py", line 131, in init_tokenizer
    tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')
  File "/opt/conda/envs/bevfusion/lib/python3.8/site-packages/transformers/tokenization_utils_base.py", line 1736, in from_pretrained
    raise EnvironmentError(msg)
OSError: Can't load tokenizer for 'bert-base-uncased'. Make sure that:

- 'bert-base-uncased' is a correct model identifier listed on 'https://huggingface.co/models'
  (make sure 'bert-base-uncased' is not a path to a local directory with something else, in that case)

- or 'bert-base-uncased' is the correct path to a directory containing relevant tokenizer files
```
